### ISSUE TITLE
在 rt-thread v5.0.1 版本下编译失败

### ISSUE THREAD

**Issue by z14git** [RT-Thread-packages/CMSIS_RTOS2#4]
很多东西没有定义
![image](https://github.com/RT-Thread-packages/CMSIS_RTOS2/assets/31793423/0c9c6bd3-e07d-4307-895c-b513c6b3b101)

**Comment by wdfk-prog** [comment]
- 需要开启legacy支持
- 不行也yongb用不了,还是得做修改支持
![image](https://github.com/user-attachments/assets/333b2bf3-4b50-4c87-803b-cade5f7c01cc)

**Comment by wdfk-prog** [comment]
> 很多东西没有定义 ![image](https://private-user-images.githubusercontent.com/31793423/267840351-0c9c6bd3-e07d-4307-895c-b513c6b3b101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MDI5MTUsIm5iZiI6MTcyNzcwMjYxNSwicGF0aCI6Ii8zMTc5MzQyMy8yNjc4NDAzNTEtMGM5YzZiZDMtZTA3ZC00MzA3LTg5NWMtYjUxM2M2YjNiMTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDEzMjMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlOGU4NjJlYmZmOWEzNzRjZGZhMTg0YmVmNTM5N2NlMzk4YjFlNDMwMGQzZTU5YTc2YzlkOGQyNTAwMjRhZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HnoCRjmQuWHzG5AdJ3PFyFZeHcU9uJ163ojNN_Q2yOM)

https://github.com/RT-Thread-packages/CMSIS_RTOS2/pull/5

我添加了一个pr修复,你可以试一下
